services:
  postgres:
    image: postgres:18
    container_name: firefly_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: firefly
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: firefly_art_studio

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: